version: "3.8"

services:
  # 1. API SERVICE
  api-service:
    build: .
    container_name: ub-linkops-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres-db
    networks:
      - ublinkops-network

  # 2. FRONTEND
  frontend-service:
    build: . # Reuse image API biar hemat
    container_name: ub-linkops-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
    environment:
      - API_URL=http://api-service:8000/match
    command: streamlit run src/frontend/app.py --server.address=0.0.0.0
    depends_on:
      - api-service
    networks:
      - ublinkops-network

  # 3. MLFLOW
  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow

    container_name: ub-linkops-mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://admin:password123@postgres-db:5432/ublinkops_db
      - MLFLOW_ARTIFACT_ROOT=/mlartifacts
    volumes:
      - ./mlruns:/mlartifacts
    depends_on:
      - postgres-db
    # Command tetap sama
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql://admin:password123@postgres-db:5432/ublinkops_db --default-artifact-root /mlartifacts
    networks:
      - ublinkops-network

  # 4. DATABASE
  postgres-db:
    image: postgres:15-alpine
    container_name: ub-linkops-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ublinkops_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ublinkops-network

  # 5. PROMETHEUS (Monitoring)
  prometheus:
    image: prom/prometheus:latest
    container_name: ub-linkops-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - ublinkops-network

  # 6. GRAFANA (Dashboard)
  grafana:
    image: grafana/grafana:latest
    container_name: ub-linkops-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - ublinkops-network

networks:
  ublinkops-network:
    driver: bridge

volumes:
  postgres_data:
